name: 'Status Check Labeling'
description: 'Label a pull request based on the results of its status checks'
author: 'Cloud Posse <hello@cloudposse.com>'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  label:
    description: "Label to add/remove (be sure to sync with labels in labeler-add.yml and labeler-remove.yml)"
    required: true
    default: "no-plan-changes"
  check-name:
    description: "String to use to identify relevant status checks"
    required: true
    default: "spacelift"
  check-description:
    description: "String that all relevant status checks descriptions must contain in order to apply the label"
    required: true
    default: "Plan contains no changes"
runs:
  using: "composite"
  steps:
#    - name: debugging
#      id: debugging
#      shell: bash
#      run: |
#        echo "pwd: $(pwd)"
#        ls -l .
#        echo "github.action_path: ${{ github.action_path }}"
#        ls -l ${{ github.action_path }} || true
#        echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
#        ls -l ${GITHUB_ACTION_PATH} || true
#        echo "github context: ${GITHUB_CONTEXT}"
#        echo "github.context: ${{ toJSON(github) }}"
#        echo '$(printenv | grep "GITHUB")'

    - name: Identify Plan Changes
      id: identify-plan-changes
      shell: bash
      run: ${{ github.action_path }}/identify_plan_changes.sh
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUTS_CHECK_DESCRIPTION: ${{ inputs.check-description }}
        INPUTS_CHECK_NAME: ${{ inputs.check-name }}

    - name: Determine Current PR Labels
      id: determine-current-pr-labels
      shell: bash
      run: ${{ github.action_path }}/determine_current_pr_labels.sh
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUTS_LABEL: ${{ inputs.label }}

#    - name: Add PR Label
#      id: add-pr-label
#      if: (! steps.determine-current-label-prs.outputs.no_changes) && (! steps.identify-plan-changes.outputs.changes)
#      uses: actions/labeler@v3
#      with:
#        configuration-path: labeler-add-example.yml
#        repo-token: "${{ secrets.GITHUB_TOKEN }}"
#
#    - name: Remove PR Label
#      id: remove-pr-label
#      if: steps.determine-current-label-prs.outputs.no_changes && steps.identify-plan-changes.outputs.changes
#      uses: actions/labeler@v3
#      with:
#        configuration-path: labeler-remove-example.yml
#        repo-token: "${{ secrets.GITHUB_TOKEN }}"
#        sync-labels: true
