name: dogfooding
#permissions:
#  issues: write

#on:
#  pull_request:
on:
  - status

jobs:
  dogfood:
    name: dogfooding
    runs-on: ubuntu-latest
    steps:
      - name: status-check-summaries
        uses: cloudposse/github-action-status-check-labeling@master
        #uses: cloudposse/actions/github/status-check-labeling@status-check-labeling
        with:
          label: "no-plan-changes"
          name-contains: "spacelift"
          description-contains: "Plan contains no changes"
          github-token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Add PR Label
#        id: add-pr-label
#        if: (! steps.dogfooding.outputs.no_changes) && (! steps.dogfooding.outputs.changes)
#        uses: actions/labeler@v3
#        with:
#          configuration-path: .github/labeler-add-example.yml
#          repo-token: "${{ secrets.GITHUB_TOKEN }}"
#      - name: Remove PR Label
#        id: remove-pr-label
#        if: steps.dogfooding.outputs.no_changes && steps.dogfooding.outputs.changes
#        uses: actions/labeler@v3
#        with:
#          configuration-path: .github/labeler-remove-example.yml
#          repo-token: "${{ secrets.GITHUB_TOKEN }}"
#          sync-labels: true
