name: dogfooding
on:
  pull_request:
jobs:
  dogfood:
    name: Dogfood
    runs-on: ubuntu-latest
    steps:
    - name: debugging
      id: debugging
      run: |
        pwd
        ls -ahltr
        ls -ahltr ./workflow
        ls -ahltr ./workflow/debugging
        cat ./workflow/debugging
        printenv | grep "GITHUB"
        echo "${{ toJson(github) }}"
    - uses: cloudposse/actions/github/status-check-labeling@status-check-labeling
      with:
        label: "no-plan-changes"
        check-name: "spacelift"
        check-description: "Plan contains no changes"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#    - name: Add PR Label
#      id: add-pr-label
#      if: (! steps.dogfooding.outputs.no_changes) && (! steps.dogfooding.outputs.changes)
#      uses: actions/labeler@v3
#      with:
#        configuration-path: .github/labeler-add-example.yml
#        repo-token: "${{ secrets.GITHUB_TOKEN }}"
#    - name: Remove PR Label
#      id: remove-pr-label
#      if: steps.dogfooding.outputs.no_changes && steps.dogfooding.outputs.changes
#      uses: actions/labeler@v3
#      with:
#        configuration-path: .github/labeler-remove-example.yml
#        repo-token: "${{ secrets.GITHUB_TOKEN }}"
#        sync-labels: true
